# on:
#     # cronjob trigger
#   schedule:
#   - cron:  "*/5 * * * *"
#   # manual trigger
#   workflow_dispatch:
# jobs:
#   repo-sync:
#     runs-on: ubuntu-latest

#     steps:
#       # To use this repository's private action, you must check out the repository
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: actions-template-sync
#         uses: AndreasAugustin/actions-template-sync@v0.1.6-draft
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           source_repo_path: amirmasoud/sample-template
#           upstream_branch: main # defaults to main

name: 'Template Sync'

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: narrowspark/template-sync-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_author_name: Sample
          git_author_email: sample@example.com
          template_repository: amirmasoud/sample-template
          ref: refs/heads/main
