name: 'Template Sync'

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: narrowspark/template-sync-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_author_name: Sample
          git_author_email: sample@example.com
          template_repository: amirmasoud/sample-template
          ref: refs/heads/main
